function onOpen() {
  var ui = SpreadsheetApp.getUi();
  ui.createMenu('Alat otomasi✨')
      .addItem('Buat TOR', 'createTOR')
      .addItem('Buat form presensi', 'createForm')
      .addToUi();
}

function createTOR() {
  // Show a popup message.
  SpreadsheetApp.getActiveSpreadsheet().toast('Adonan TOR-nya lagi dimasak🍰');

  //This value should be the id of your document template that we created in the last step
  const googleDocTemplate = DriveApp.getFileById('put_my_doc_id_here');
  
  //This value should be the id of the folder where you want your completed documents stored
  const destinationFolder = DriveApp.getFolderById('put_my_folder_id_here')
  //Here we store the sheet as a variable
  const sheet = SpreadsheetApp
    .getActiveSpreadsheet()
    .getSheetByName('put_my_sheet_name_here)
  
  //Now we get all of the values as a 2D array
  const rows = sheet.getDataRange().getValues();
  
  //Start processing each spreadsheet row
  rows.forEach(function(row, index){
    //Here we check if this row is the headers, if so we skip it
    if (index === 0) return;
    if (index === 1) return;
    if (index === 2) return;
    if (index === 3) return;
    if (index === 4) return;
    if (index === 5) return;
    if (index === 6) return;
    if (index === 7) return;
    if (index === 8) return;
    if (index === 9) return;
    if (index === 10) return;
    if (index === 11) return;
    if (index === 12) return;

    //Here we check if a document has already been generated by looking at 'Document Link', if so we skip it
    if (row[7]) return;
    if (!row[2]) return;
    if (!row[3]) return;
    
    //Using the row data in a template literal, we make a copy of our template document in our destinationFolder
    const copy = googleDocTemplate.makeCopy(`Custom Title Here - ${row[3]}` , destinationFolder)
    //Once we have the copy, we then open it using the DocumentApp
    const doc = DocumentApp.openById(copy.getId())
    //All of the content lives in the body, so we get that for editing
    const body = doc.getBody();
    
    //In these lines, we replace our replacement tokens with values from our spreadsheet row
    body.replaceText('{{Token 1}}', row[2]);
    body.replaceText('{{Token 2}}', row[3]);
    body.replaceText('{{Token 3}}', row[4]);
    body.replaceText('{{Token 4}}', row[5]);
    
    //We make our changes permanent by saving and closing the document
    doc.saveAndClose();
    //Store the url of our new document in a variable
    const url = doc.getUrl();
    //Write that value back to the 'Document Link' column in the spreadsheet. 
    sheet.getRange(index + 1, 8).setValue(url)
    
  })
  
}
